name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token: # id of input
    description: 'github token'
    required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
