name: "Create Daily plan Issue"
description: "automatic create daily plan issue for Leiloloaa/daily-plan"
# inputs:
#   token: # id of input
#     description: 'github token'
#     required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
