name: 'Create Study Every Day Issue'
description: 'automatic create study every day issue for Leiloloaa/study-every-day'
inputs:
  token:
    description: 'github token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
